version: '3.8'
services:
  terraform:
    image: hashicorp/terraform:0.12.28
    volumes:
     - .:/project
    working_dir: /project
    entrypoint:
      - /bin/sh
      - -c
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env_file:
      - .env
